# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13S7zkIHPAGvCKeZMPOR7Axb5nJ7dTvGN
"""

import streamlit as st

st.set_page_config(page_title="Halaman Pertama", layout="centered")
st.sidebar.header("Halaman Pertama")

